// <auto-generated />
using System;
using LanchesMac.context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LanchesMac.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260221201651_Seed")]
    partial class Seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LanchesMac.Models.CarrinhoCompraItem", b =>
                {
                    b.Property<int>("CarrinhoCompraItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CarrinhoCompraItemId"));

                    b.Property<string>("CarrinhoCompraId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("LancheId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.HasKey("CarrinhoCompraItemId");

                    b.HasIndex("LancheId");

                    b.ToTable("CarrinhoCompraITens");
                });

            modelBuilder.Entity("LanchesMac.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("CategoriaNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            CategoriaId = 1,
                            CategoriaNome = "Normal",
                            Descricao = "Lanche feito com ingredientes normais"
                        },
                        new
                        {
                            CategoriaId = 2,
                            CategoriaNome = "Natural",
                            Descricao = "Lanche feito com ingredientes integrais e naturais"
                        });
                });

            modelBuilder.Entity("LanchesMac.Models.Lanche", b =>
                {
                    b.Property<int>("LancheId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LancheId"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("DescricaoCurta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DescricaoDetalhada")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("EmEstoque")
                        .HasColumnType("boolean");

                    b.Property<string>("ImagemThumbnailUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ImagemUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsLanchePreferido")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("LancheId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Lanches");

                    b.HasData(
                        new
                        {
                            LancheId = 1,
                            CategoriaId = 1,
                            DescricaoCurta = "Pão, hambúrger, ovo, presunto, queijo e batata palha",
                            DescricaoDetalhada = "Delicioso pão de hambúrger com ovo frito; presunto e queijo de primeira qualidade acompanhado com batata palha",
                            EmEstoque = true,
                            ImagemThumbnailUrl = "http://www.macoratti.net/Imagens/lanches/cheesesalada1.jpg",
                            ImagemUrl = "http://www.macoratti.net/Imagens/lanches/cheesesalada1.jpg",
                            IsLanchePreferido = false,
                            Nome = "Cheese Salada",
                            Preco = 12.50m
                        },
                        new
                        {
                            LancheId = 2,
                            CategoriaId = 1,
                            DescricaoCurta = "Pão, presunto, mussarela e tomate",
                            DescricaoDetalhada = "Delicioso pão francês quentinho na chapa com presunto e mussarela bem servidos com tomate preparado com carinho.",
                            EmEstoque = true,
                            ImagemThumbnailUrl = "http://www.macoratti.net/Imagens/lanches/mistoquente4.jpg",
                            ImagemUrl = "http://www.macoratti.net/Imagens/lanches/mistoquente4.jpg",
                            IsLanchePreferido = false,
                            Nome = "Misto Quente",
                            Preco = 8.00m
                        },
                        new
                        {
                            LancheId = 3,
                            CategoriaId = 1,
                            DescricaoCurta = "Pão, hambúrger, presunto, mussarela e batalha palha",
                            DescricaoDetalhada = "Pão de hambúrger especial com hambúrger de nossa preparação e presunto e mussarela; acompanha batata palha.",
                            EmEstoque = true,
                            ImagemThumbnailUrl = "http://www.macoratti.net/Imagens/lanches/cheeseburger1.jpg",
                            ImagemUrl = "http://www.macoratti.net/Imagens/lanches/cheeseburger1.jpg",
                            IsLanchePreferido = false,
                            Nome = "Cheese Burger",
                            Preco = 11.00m
                        },
                        new
                        {
                            LancheId = 4,
                            CategoriaId = 2,
                            DescricaoCurta = "Pão Integral, queijo branco, peito de peru, cenoura, alface, iogurte",
                            DescricaoDetalhada = "Pão integral natural com queijo branco, peito de peru e cenoura ralada com alface picado e iorgurte natural.",
                            EmEstoque = true,
                            ImagemThumbnailUrl = "http://www.macoratti.net/Imagens/lanches/lanchenatural.jpg",
                            ImagemUrl = "http://www.macoratti.net/Imagens/lanches/lanchenatural.jpg",
                            IsLanchePreferido = true,
                            Nome = "Lanche Natural Peito Peru",
                            Preco = 15.00m
                        });
                });

            modelBuilder.Entity("LanchesMac.Models.CarrinhoCompraItem", b =>
                {
                    b.HasOne("LanchesMac.Models.Lanche", "Lanche")
                        .WithMany()
                        .HasForeignKey("LancheId");

                    b.Navigation("Lanche");
                });

            modelBuilder.Entity("LanchesMac.Models.Lanche", b =>
                {
                    b.HasOne("LanchesMac.Models.Categoria", "Categoria")
                        .WithMany("Lanches")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("LanchesMac.Models.Categoria", b =>
                {
                    b.Navigation("Lanches");
                });
#pragma warning restore 612, 618
        }
    }
}
